apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    project: spaced-repetition
    role: web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
        project: spaced-repetition
        role: web-app
  template:
    metadata:
      labels:
        project: spaced-repetition
        role: web-app
    spec:
      containers:
        - name: spaced-repetition-app
          image: aeissa/spaced-repetition-app
